name: Validate HTML and CSS
on:
  push:
    branches: [ master, develop ]
  pull_request:
jobs:
  w3c-validate:
    name: Validates HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate files
        uses: Cyb3r-Jak3/html5validator-action@v0.4.4
        with:
          root: /
          css: true
          format: text
          log_level: INFO
